version: '3'

volumes:
  postgres-data:
  minio-data:

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prova
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minioaccesskey
      MINIO_SECRET_KEY: miniosecretkey
    volumes:
      - minio-data:/data
    ports:
      - "9008:9000"
      - "9009:9001"
    command: server /data --console-address ":9001"

  jupyter:
    image: jupyter/pyspark-notebook
    volumes:
      - ./notebooks:/home/jovyan/notebooks
    ports:
      - "8888:8888"
    depends_on:
      - postgres
      - minio
    command: start.sh jupyter lab --LabApp.base_url=/ --LabApp.token='token'